### ISSUE TITLE
Linking error at runtime

### ISSUE THREAD

**Issue by bylowerik** [VoysAI/tflitec-rs#15]
I have added `tflitec = "0.5.2"` to my `Cargo.toml`. It builds finally when I used bazelisk instead of bazel. 

When I run my compiled program, I get the error 

```
./target/debug/my-main
dyld[55052]: Library not loaded: @rpath/libtensorflowlite_c.dylib
  Referenced from: <C2FD8DBC-DF01-3A15-8576-04747D0C47D8> /Users/erikbylow/Code/Git/GolfApp/web-golf/backend/app/target/debug/my-main
  Reason: tried: '/System/Volumes/Preboot/Cryptexes/OS@rpath/libtensorflowlite_c.dylib' (no such file), '/usr/local/lib/libtensorflowlite_c.dylib' (no such file), '/usr/lib/libtensorflowlite_c.dylib' (no such file, not in dyld cache)
[1]    55052 abort      ./target/debug/my-main

```
If I run 

`export DYLD_LIBRARY_PATH=target/debug/build/tflitec-6528b88bf0f2f543/out/`

it finds the library and runs as expected. 

Would be nice if this could be automatic.

**Comment by ebraraktas** [comment]
Thanks for your feedback. 

The thing is I had the same issue, and as a workaround I use `cargo run` to invoke binary targets. As it is documented [here](https://doc.rust-lang.org/cargo/reference/environment-variables.html#dynamic-library-paths), cargo adds necessary paths to library search paths. I am aware that this is [not the best practice](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-search:~:text=Depending%20on%20this%20behavior%20is%20discouraged), but to my knowledge I cannot build static `TensorFlowLiteC` right now. 

As I stated earlier, I suggest you to do one of following:

*  Use `cargo run` instead of invoking a binary under `target`.
* Copy built `libtensorflowlite_c.{dylib,so}` to one of the system library search paths (such as `/usr/lib` or `/usr/local/lib`).

Nevertheless, it is better to document this in the README.

**Comment by ebraraktas** [comment]
Documented [here](https://github.com/VoysAI/tflitec-rs#linking).
