### ISSUE TITLE
Lifetimes make usage in structs hard

### ISSUE THREAD

**Issue by stexa** [VoysAI/tflitec-rs#20]
How would you solve this problem?

```Rust
struct TfLiteInferenceEngine<'a> {
    model: Model<'a>,
    interpreter: Interpreter<'a>,
}

impl TfLiteInferenceEngine<'_> {
    pub fn new() -> Self {
        let model = Model::new("model.tflite").unwrap();
        let interpreter = Interpreter::new(&model, Some(Options { thread_count: 1 })).unwrap();
        Self {
            model,
            interpreter,
        }
    }
}
```

Gives the error: 

```
error[E0597]: `model` does not live long enough

   |
23 | impl<'a> TfLiteInferenceEngine for TfLiteInferenceEngine<'a> {
   |      -- lifetime `'a` defined here
...
38 |             interpreter: Interpreter::new(&model, Some(Options { thread_count: 1 }))?,
   |                          -----------------^^^^^^-------------------------------------
   |                          |                |
   |                          |                borrowed value does not live long enough
   |                          this usage requires that `model` is borrowed for `'a`
...
57 |     }
   |     - `model` dropped here while still borrowed

error[E0505]: cannot move out of `model` because it is borrowed

   |
23 | impl<'a> TfLiteInferenceEngine for TfLiteInferenceEngine<'a> {
   |      -- lifetime `'a` defined here
...
38 |             interpreter: Interpreter::new(&model, Some(Options { thread_count: 1 }))?,
   |                          ------------------------------------------------------------
   |                          |                |
   |                          |                borrow of `model` occurs here
   |                          this usage requires that `model` is borrowed for `'a`
39 |             model,
   |             ^^^^^ move out of `model` occurs here

```

**Comment by ebraraktas** [comment]
What you are trying to build is a [self referential struct](https://stackoverflow.com/questions/72562870/how-can-i-write-a-self-referential-rust-struct-with-arc-and-bufreader#:~:text=Self%2Dreferential%20structs%20are%20a%20no%2Dgo) and to my knowledge you cannot do that. I suggest you refactoring your code so that a struct holding the `Model` creates an `Interpreter` when necessary.

**Comment by stexa** [comment]
For my usecase that was working fine, as I only need one model:

```
lazy_static! {
    static ref MODEL: Model<'static> = Model::new("model.tflite").unwrap();
}
```

**Comment by fredo838** [comment]
I've been stuck on this a couple of days, trying to wrap my head around this. How is this a self-referential struct, and how would you refactor this code to create the `Interpreter` when necessary? 

Just to give some context, I'm having trouble keeping the `Interpreter` loaded in `actix_web`: ```
#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(move || {
        let model = Model::new("model.tflite").unwrap();
        let interpreter = Interpreter::new(&model, Some(Options::default())).unwrap();
        interpreter.allocate_tensors();
        let counter_cell = Cell::new(interpreter);
        App::new().app_data(Data::new(counter_cell)).service(hello)
    })
    .bind(("0.0.0.0", 8000))?
    .run()
    .await
}
```

Just some pointers on how to solve this would already help, thanks. I tried https://users.rust-lang.org/t/how-can-we-teach-people-about-self-referential-types/65362 but it's still chinese to me.

**Comment by fredo838** [comment]
When I use the `0.5.2` version, this does compile (with `from_modelpath`), so I'm feeling it has nothing to do with self referencing. It's clearly something with the lifetimes you added in this commit https://github.com/VoysAI/tflitec-rs/commit/f2b1d318c2268dc9a5b1b20d1e57ab4750765bec (the one with the breaking change). I'm just wondering why this version does not compile this code, while the other does. I guess the reason is the (from https://github.com/tensorflow/tensorflow/issues/53628) "the model data must outlive the `Interpreter`", but is there a way to enforce that if `Interpreter::new(&model)` uses a borrow?

**Comment by fredo838** [comment]
It compiles, and also works on `0.5.2`. I was expecting `model` to be deallocated when the main function finishes, but as it never finishes becomes the program runs indefinitely, it's never deallocated? I'm feeling like this is the hard part about learning Rust, and I can't wrap my head around it. @ebraraktas if you feel like giving this a change, I would be happy to make a PR that includes an example of "serving a tflitec model with Rust actix_web".

**Comment by ebraraktas** [comment]
Hi @fredo838 . Thanks for your interest. Let me try to answer the points you asked:

* First, as you said this was not an issue before `0.6.0`, but those were not safe. Because you could do something like below:
```rust
let model = Model::new("tests/add.bin")?;
// Create interpreter
let interpreter = Interpreter::new(&model, Some(options))?;
drop(model) // This drops model explicitly. 
// From now on, you can compile and run the code below
// but it is not safe because you deallocated the model 
// on which the interpreter depends.
interpreter.invoke()
```
And as it is stated in [the official tensorflow documentation](https://www.tensorflow.org/lite/api_docs/cc/namespace/tflite#namespacetflite_1a2d6d829bce5eba5b241987ca5b4f0f40) this is against the design of the public TensorFlow API. As you wrote, this kind of code was working because internal TensorFlow implementation handled models initialized from filesystem differently. And we cannot depend on that implementation detail. And the issue you linked demonstrates other unsafe usages when you create a model from an array in memory.
* The code snipped you posted is not about self referential struct, actually. I added some comments describing the issue:
```rust
#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(move || {
        // Lifetime of the model is limited by this context
        let model = Model::new("model.tflite").unwrap();
        let interpreter = Interpreter::new(&model, Some(Options::default())).unwrap();
        interpreter.allocate_tensors();
        let counter_cell = Cell::new(interpreter);
        App::new().app_data(Data::new(counter_cell)).service(hello)
        // and model must be dropped here, but borrow checker doesn't allow you to do that
        // because you are moving the interpreter outside of this context and interpreter depends 
        // on the model
    })
    .bind(("0.0.0.0", 8000))?
    .run()
    .await
}
```
So you need to ensure that the `model` lives as long as your web app lives. And one way to do that is moving `model` inside `Data`. However, you cannot put the `model` and an `Interpreter` depending on it to the same `Data`, that would be a self referential struct:
```rust
// This is not allowed, interpreter cannot point to the model
struct AppData<'a> {
  model: Model<'a>
  interpreter: <'a>
}
// ...
{
//..
  HttpServer::new(move || {
        // create model and interpterter
        let data = AppData { model, interpreter };
        App::new().app_data(Data::new(data)).service(hello)
    })
// .. 
```
* Aside from the lifetime issues, `Interpreter` is **not** thread safe, as documented [here](https://docs.rs/tflitec/latest/tflitec/interpreter/struct.Interpreter.html). Hence I recommend creating one for each request. Otherwise you need to block other requests incoming concurrently (and you need some kind of `Mutex` to lock it). Here is the most concise example I could come up with:
```rust
use actix_web::web::Data;
use actix_web::{get, App, HttpResponse, HttpServer, Responder};
use tflitec::interpreter::Interpreter;
use tflitec::model::Model;

#[get("/")]
async fn hello(data: Data<Model<'static>>) -> impl Responder {
    // Create interpreter from the data
    let interpreter = Interpreter::new(&data, None).unwrap();
    // Run it and return the first element of the output tensor
    interpreter.allocate_tensors().unwrap();
    // 192 is the model input size, you need to update it for your model
    interpreter.copy(&[1.0_f32; 192], 0).unwrap();
    interpreter.invoke().unwrap();
    let output = interpreter.output(0).unwrap();
    HttpResponse::Ok().body(format!("Result: {}", output.data::<f32>()[0]))
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(move || {
        // Create a model from the test model resource
        let model = Model::new("../../tests/add.bin").unwrap();
        // Move model to the app data and create interpreter inside request handler
        App::new().app_data(Data::new(model)).service(hello)
    })
    .bind(("0.0.0.0", 8000))?
    .run()
    .await
}
```
* About your question:
> It compiles, and also works on 0.5.2. I was expecting model to be deallocated when the main function finishes, but as it never finishes becomes the program runs indefinitely, it's never deallocated? 
I think this is the intended behavior for a web app, I mean you would to have model available as long as the lifetime of the app so that you can serve it (or the result calculated from an interpreter created from it).

**Comment by fredo838** [comment]
@ebraraktas Thank you so much for your feedback! This has helped me a lot in the past few days, and helped my at least understand what a self-referential struct is and why it can't be in Rust.

But now the lifetimes - I actually _want_ what you said here: `Otherwise you need to block other requests incoming concurrently (and you need some kind of Mutex to lock it)`. I need the `Interpreter` inside the `Data` object, and that's only possible behind a `Mutex`, as you said. But I can't add a `Mutex<Interpreter>` inside the `Data` either because of the litetimes. I need it because `allocate_tensors` needs to happen at startup time, not at inference time. (If I see that my application needs more that one `Interpreter` to serve all the requests, I'll need to instantiate multiple models (each calling `allocate_tensors()`), but it's critical for me that this `allocate_tensors()` happens before any requests can be served to it.). 

Do you see a way to solve these lifetime issues? I feel like it's the key to understanding lifetimes for me. Thank you very much already for your time!

**Comment by ebraraktas** [comment]
@fredo838 Here is an example using `lazy_static`:

```rust
use actix_web::web::Data;
use actix_web::{get, App, HttpResponse, HttpServer, Responder};
use tflitec::interpreter::Interpreter;
use tflitec::model::Model;
use lazy_static::lazy_static;

lazy_static! {
    static ref MODEL: Model<'static> = Model::new("../../tests/add.bin").unwrap();
}


#[get("/")]
async fn hello(interpreter: Data<Interpreter<'static>>) -> impl Responder {
    interpreter.copy(&[1.0_f32; 192], 0).unwrap();
    interpreter.invoke().unwrap();
    let output = interpreter.output(0).unwrap();
    HttpResponse::Ok().body(format!("Result: {}", output.data::<f32>()[0]))
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(move || {
        let interpreter = Interpreter::new(&MODEL, None).unwrap();
        interpreter.allocate_tensors().unwrap();
        App::new().app_data(Data::new(interpreter)).service(hello)
    })
    .bind(("0.0.0.0", 8000))?
    .run()
    .await
}
```

**Comment by fredo838** [comment]
This is what I have now:
```
error[E0277]: the trait bound `for<'a> fn(Json<MyData>, Data<MyInterpreter<'a>>) -> HttpResponse {hello}: HttpServiceFactory` is not satisfied
   --> src/main.rs:65:22
    |
65  |             .service(hello)
    |              ------- ^^^^^ the trait `HttpServiceFactory` is not implemented for fn item `for<'a> fn(Json<MyData>, Data<MyInterpreter<'a>>) -> HttpResponse {hello}`
    |              |
    |              required by a bound introduced by this call
    |
    = help: the following other types implement trait `HttpServiceFactory`:
              Resource<T>
              actix_web::Scope<T>
              Vec<T>
              Redirect
              (A,)
              (A, B)
              (A, B, C)
              (A, B, C, D)
            and 8 others
note: required by a bound in `App::<T>::service`
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-web-4.4.0/src/app.rs:238:12
    |
236 |     pub fn service<F>(mut self, factory: F) -> Self
    |            ------- required by a bound in this associated function
237 |     where
238 |         F: HttpServiceFactory + 'static,
    |            ^^^^^^^^^^^^^^^^^^ required by this bound in `App::<T>::service`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `server` (bin "server") due to previous error
```

but the lifetimes are still giving me issues:

```
error[E0277]: the trait bound `for<'a> fn(Json<MyData>, Data<MyInterpreter<'a>>) -> HttpResponse {hello}: HttpServiceFactory` is not satisfied
   --> src/main.rs:65:22
    |
65  |             .service(hello)
    |              ------- ^^^^^ the trait `HttpServiceFactory` is not implemented for fn item `for<'a> fn(Json<MyData>, Data<MyInterpreter<'a>>) -> HttpResponse {hello}`
    |              |
    |              required by a bound introduced by this call
    |
    = help: the following other types implement trait `HttpServiceFactory`:
              Resource<T>
              actix_web::Scope<T>
              Vec<T>
              Redirect
              (A,)
              (A, B)
              (A, B, C)
              (A, B, C, D)
            and 8 others
note: required by a bound in `App::<T>::service`
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-web-4.4.0/src/app.rs:238:12
    |
236 |     pub fn service<F>(mut self, factory: F) -> Self
    |            ------- required by a bound in this associated function
237 |     where
238 |         F: HttpServiceFactory + 'static,
    |            ^^^^^^^^^^^^^^^^^^ required by this bound in `App::<T>::service`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `server` (bin "server") due to previous error
```
