### ISSUE TITLE
Question on copying the header files. 

### ISSUE THREAD

**Issue by fredo838** [VoysAI/tflitec-rs#25]
In `build.rs`, two header files `c_api.h` and `c_api_types.h` get downloaded/copied from Github (or four files if you include xnnpack). 

The documentation states that we need some other files as well, found here, all the way at the bottom in the Note. https://www.tensorflow.org/lite/guide/build_cmake:
```
Note: You need the public headers (tensorflow/lite/c_api.h, tensorflow/lite/c_api_experimental.h, tensorflow/lite/c_api_types.h, and tensorflow/lite/common.h), and the private headers that those public headers include (tensorflow/lite/core/builtin_ops.h, tensorflow/lite/core/c/*.h, and tensorflow/lite/core/async/c/*.h, ) to use the generated shared library.
```
But everything still works. Do you have any idea why?

**Comment by ebraraktas** [comment]
Yes, because the current version of the crate still builds `v2.9.1` of `tensorflow`, see the line below https://github.com/VoysAI/tflitec-rs/blob/d3f4cd8623436b0083f715c5439c96511f5c0c77/build.rs#L9
and it requires the headers listed below: https://github.com/VoysAI/tflitec-rs/blob/d3f4cd8623436b0083f715c5439c96511f5c0c77/build.rs#L415-L418

I plan to make the `TAG` configurable by an environment variable in the next release.

**Comment by fredo838** [comment]
Thank you very much!
